### ISSUE TITLE
Crash when de_DE locale is not installed

### ISSUE THREAD

**Issue by alexis-via** [manuelRiel/invoice2data#1]
I am trying to use invoice2data on my Ubuntu 15.10:

```
% python -m invoice2data.main invoice2data/test/pdfs --debug
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 67, in <module>
    res = extract_data(join(args.file_folder, f))
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 34, in extract_data
    output[k] = str2date(raw_date)
  File "invoice2data/date_parser.py", line 33, in str2date
    with setlocale(l):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "invoice2data/date_parser.py", line 18, in setlocale
    yield locale.setlocale(locale.LC_ALL, name)
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
zsh: exit 1     python -m invoice2data.main invoice2data/test/pdfs --debug
```
As I am a French user, my default locale is French:
```
% locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

If I run "locale-gen", I see that Ubuntu generate all fr_* and en_* locales.

The crash is linked to the fact that you try to set the locale de_DE. In date_parser.py line 32, if I remove 'de_DE.UTF-8' from the list, I will manage to parse the 2 first invoices, but it will crash later on:

```
% python -m invoice2data.main invoice2data/test/pdfs --debug
{'date': datetime.datetime(2014, 8, 3, 0, 0), 'invoice_number': '42183017', 'amount': 4.11, 'desc': 'Invoice 42183017 from Amazon Web Services'}
{'date': datetime.datetime(2015, 1, 28, 0, 0), 'invoice_number': '12429647', 'amount': 101.0, 'desc': 'Invoice 12429647 from Envato'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 67, in <module>
    res = extract_data(join(args.file_folder, f))
  File "/home/alexis/new_boite/dev/invoice2data/invoice2data/main.py", line 38, in extract_data
    output[k] = re.findall(v, str)[0]
IndexError: list index out of range
zsh: exit 1     python -m invoice2data.main invoice2data/test/pdfs --debug
```

**Comment by manuelRiel** [comment]
Hi Alexis,

thanks for the detailed report. I'll test it out this week.
